language: node_js

node_js:
  - node

cache: yarn

sudo: required

services:
  - docker

before_install:
  - docker pull dgraph/dgraph
  - docker run -d -p 8080:8080 --name dgraph dgraph/dgraph dgraph --bindall=true

after_success:
  - if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
