language: node_js

node_js:
  - node

cache: yarn

sudo: required

services:
  - docker

before_install:
  - docker pull dgraph/dgraph
  - docker run -d -p 8080:8080 --name dgraph dgraph/dgraph dgraph --bindall=true --memory_mb=1024

after_success:
  - ./node_modules/.bin/codecov
